spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wang
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#logging:
#  pattern:
#    console: "%d - %msg %n"
#  file: log
#  level:
#    com.wang.sell.LoggerTest: debug
server:
  servlet:
    context-path: /sell
